name: testing on pull request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  snowflake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - uses: abatilo/actions-poetry@a5643c67b5fcc9ac5eddb395c7f61b1b66d86034  # abatilo/actions-poetry@v2
        with:
          poetry-version: 1.7.1

      - name: Install dependencies
        run: |
          poetry config installer.max-workers 1
          poetry config virtualenvs.in-project true
          poetry install
          mkdir ~/.dbt
          cp integration_tests/ci/ci.profiles.yml ~/.dbt/profiles.yml

      - name: Code Quality
        run: |
          poetry run poe lint

      - name: Test dbt tags
        run: |
          poetry run poe dbt-tags-test
        env:
          DBT_SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_TEST_ACCOUNT }}
          DBT_SNOWFLAKE_TEST_USER: ${{ secrets.DBT_SNOWFLAKE_TEST_USER }}
          DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD: ${{ secrets.DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD }}
          DBT_SNOWFLAKE_TEST_ROLE: ${{ secrets.DBT_SNOWFLAKE_TEST_ROLE }}
          DBT_SNOWFLAKE_TEST_DATABASE: ${{ secrets.DBT_SNOWFLAKE_TEST_DATABASE }}
          DBT_SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_TEST_WAREHOUSE }}
          DBT_SCHEMA: PRCI_${{ github.sha }}
